version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: org_management_api
    env_file:
      - .env.docker
    ports:
      - 9090:9090
    depends_on:
      - postgresdb
    links:
      - postgresdb
    volumes:
      - gomod:/go/pkg/mod
  postgresdb:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pkg/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/postgresql/data

volumes:
  gomod:
