version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: org_management_api
    env_file:
      - .env.docker
    ports:
      - 9090:9090
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgresdb
    networks:
      - mynetwork
  postgresdb:
    container_name: postgresdb
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pkg/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgresdb:

networks:
  mynetwork:
    driver: bridge