version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: org_management_api
    restart: on-failure
    env_file:
      - .env.docker
    ports:
      - 9090:9090
    depends_on:
      - postgresdb
    links:
      - postgresdb
  postgresdb:
    container_name: postgresdb
    image: postgres:14.3
    restart: always
    env_file:
      - .env.docker
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_USER: ${DB_USERNAME}
      # POSTGRES_DB: ${DB_NAME}
      # PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pkg/db/init.sql:/docker-entrypoint-initdb.d/init.sql
