// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/andresuchitra/org-mgmt/models"
	mock "github.com/stretchr/testify/mock"
)

// OrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type OrganizationRepository struct {
	mock.Mock
}

// GetOrganizationByName provides a mock function with given fields: ctx, name
func (_m *OrganizationRepository) GetOrganizationByName(ctx context.Context, name string) (*models.Organization, error) {
	ret := _m.Called(ctx, name)

	var r0 *models.Organization
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Organization); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
