// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/andresuchitra/org-mgmt/models"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetMembersByOrganizationID provides a mock function with given fields: ctx, organizationID
func (_m *UserRepository) GetMembersByOrganizationID(ctx context.Context, organizationID int64) ([]models.UserWithFollower, error) {
	ret := _m.Called(ctx, organizationID)

	var r0 []models.UserWithFollower
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.UserWithFollower); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserWithFollower)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
